# Generated by Django 4.1.13 on 2024-07-01 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieRec', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetRecomondation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('descripton', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
