# Generated by Django 4.1.13 on 2024-07-01 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieRec', '0002_getrecomondation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GetRecomondation',
        ),
    ]
