# Generated by Django 4.1.13 on 2024-07-01 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieRec', '0004_genre_movie_genere'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genere',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
