# Generated by Django 4.1.13 on 2024-07-01 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieRec', '0005_remove_movie_genere_delete_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genere',
            field=models.TextField(blank=True),
        ),
    ]
