# Generated by Django 4.1.13 on 2024-07-02 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieRec', '0011_alter_movie_date_alter_movie_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
