# Generated by Django 5.0.6 on 2024-07-03 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieRec', '0016_userprofile_current_movie_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='current_movie_collection',
        ),
    ]
