# Generated by Django 5.0.6 on 2024-07-03 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieRec', '0017_remove_userprofile_current_movie_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='top10_Favorite_movies',
            field=models.TextField(blank=True, null=True),
        ),
    ]
