# Generated by Django 4.1.13 on 2024-07-07 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieRec', '0018_userprofile_top10_favorite_movies'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='moviesInColelction',
            field=models.TextField(blank=True, null=True),
        ),
    ]
