# Generated by Django 4.1.13 on 2024-07-07 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieRec', '0019_userprofile_moviesincolelction'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster_path',
            field=models.TextField(blank=True),
        ),
    ]
