# Generated by Django 4.1.13 on 2024-07-07 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieRec', '0020_movie_poster_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False),
        ),
    ]
